### ISSUE TITLE
Motif enrichment in the co-accessible sites 

### ISSUE THREAD

**Issue by momur** [cole-trapnell-lab/cicero-release#101]
Hello dev team, 

Thanks for the tool. I would like to retrieve an information that I couldnt find in the tutorial page. I am interested in a particular gene and motifs observed in the co-accessible sites of that particular gene. Can you please let me know how I can get that information? 

Sorry in advance if this information already included in the tutorial page and I missed it!

**Comment by hpliner** [comment]
Apologies for the long delay. If you're looking for motifs, that's not something that's supported in Cicero. If it's a particular gene you're looking at, you may be able to find that information in the UCSC genome browser or similar resource. Reopen if I've misunderstood
