### ISSUE TITLE
Error: is(object = cds, class2 = "CellDataSet") is not TRUE

### ISSUE THREAD

**Issue by GaF123** [cole-trapnell-lab/cicero-release#103]
> umap_coords <- reducedDims(input_cds)$UMAP
> cicero_cds <- make_cicero_cds(input_cds, reduced_coordinates = umap_coords)
Error: is(object = cds, class2 = "CellDataSet") is not TRUE

And my package version is:
> packageVersion("cicero")
[1] '1.20.0'
> packageVersion("monocle3")
[1] '1.3.1'

Thank you!

**Comment by hpliner** [comment]
If you're using monocle3, then you need to be using cicero for monocle3, which would have version 1.3.9 - see the installation instructions to install from github: https://cole-trapnell-lab.github.io/cicero-release/docs_m3/#installing-cicero Be sure to restart your session after installation

Reopen if this doesn't solve the issue
