### ISSUE TITLE
ERROR:duplicate 'row.names' are not allowed

### ISSUE THREAD

**Issue by yxaxaxa** [cole-trapnell-lab/cicero-release#22]
Dear Sir:
I was trying to use Cicero to get gene activity score, however, when I follow the tutorial in the website, I encounter an error, when I began to process make_cicero_cds module, after input all the variable like tutorial and begin the chunk ,
the console report like this:
Overlap QC metrics:
Cells per bin: 50
Maximum shared cells bin-bin: 44
Mean shared cells bin-bin: 3.82782937736498
Median shared cells bin-bin: 0
NAs introduced by coercionnon-unique value when setting 'row.names': 'Peak'Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed

I was wondering which step I was wrong, as I checked all the annotate files and peakinfo, there is no duplicate index
Could you please help me to find how can I check the duplicate row or how to fix this issue?
eager for your help

                                                                                                                                     thanks

**Comment by hpliner** [comment]
Apologies for the delay. Can you please post the output of `traceback()` after running the above? Also please post the exact call you are making and if possible the heads of the inputs.

**Comment by yxaxaxa** [comment]
Sorry for late reply,
I have just check the error which shows that I may have duplicated rows
so I redo a qulity check to my raw data, and eliminate some poor quality peak,
it's now successfully entered to next step
thanks
