### ISSUE TITLE
Error in reduce dimension part of trajectory analysis

### ISSUE THREAD

**Issue by smanne07** [cole-trapnell-lab/cicero-release#24]
Hi Hannah,
Thank you for creating this useful package for scATACseq data.

I have created a celldataset going through the Cicero method and used the same object for running trajectory analysis and got the following error 

`Error in as.igraph.vs(graph, nodes) : Invalid vertex names
Calls: reduceDimension ... learnGraph -> project2MST -> neighborhood -> as.igraph.vs`

Can you help figuring out what might be causing this issue?

Thank you
Sasi

**Comment by hpliner** [comment]
Hi Sasi,

Can you please:
- post the call that's erroring
- post the traceback of the error (run traceback() after the error comes up)
- let me know if you've tried running the example on the website and if the same error occurred

Thanks,
hannah

**Comment by hpliner** [comment]
Please reopen with the requested information if this is still an issue!

Best,
Hannah
