### ISSUE TITLE
Handling large dataset

### ISSUE THREAD

**Issue by marianogabitto** [cole-trapnell-lab/cicero-release#29]
Hello,
   I am wondering, what would you recommend to create a cicero object for a dataset that is ~150k regions by 40k cells. The data is currently stored as a csv files in the proper cicero data format (location, barcode, number of reads).

    In different computer clusters, when I tried to load the data, I encountered a segmentation error (memory error).

Thanks,

**Comment by hpliner** [comment]
We are in the process of migrating from a monocle framework to a monocle3 framework, which handles large datasets much better. We hope to have that out in the next couple weeks

**Comment by hpliner** [comment]
Hello, The monocle3 version of Cicero is now live. See the instructions here https://cole-trapnell-lab.github.io/cicero-release/docs_m3/ and reopen if this is still an issue!
