### ISSUE TITLE
make_atac_cds:  fData(atac_cds)$chr <- as.numeric(as.character(fData(atac_cds)$chr))

### ISSUE THREAD

**Issue by cbravo93** [cole-trapnell-lab/cicero-release#3]
Hi,

If having sex chromosomes ('X', 'Y') this line in make_atac_cds results in the chromosome name stored as NA, which results in further errors later on. Changing it to fData(atac_cds)$chr <- as.character(fData(atac_cds)$chr) seems to work.

Cheers!

**Comment by hpliner** [comment]
Good catch! Should be fixed now!
