### ISSUE TITLE
Compatibility with Monocle3

### ISSUE THREAD

**Issue by jeremycfd** [cole-trapnell-lab/cicero-release#30]
Hello,

I went through the trouble of getting Monocle3 installed in hopes of using some of its features, including easily generating TSNE and tree plots that encode locus accessibility via color. The Cicero website suggests that Monocle3 is compatible and you simple need to add in an extra command:
```
*** if you are using Monocle 3, you need to run the following line as well!
#input_cds <- preprocessCDS(input_cds, norm_method = "none")
```
That command doesn't exist (closest thing I can find is preprocess_cds(), but "none" is not a valid norm_method for that function). Other commands like detectGenes and estimateSizeFactors also generate errors. I also couldn't figure out how to set a comparable expressionFamily.

Is Cicero simply not compatible with Monocle3?

Thanks!

**Comment by hpliner** [comment]
Hello,

Apologies for the confusion. Cicero is currently compatible with the old monocle 3 alpha branch of monocle, but not yet with monocle 3 (we're working on it and will hopefully have it available shortly). That note on the website was added before Monocle 3 was its own package. I will amend it to be more clear.

Stay tuned!

**Comment by sameet** [comment]
I tried to follow the example on the site, but I got the following error: 

    > input_cds <- input_cds[Matrix::rowSums(exprs(input_cds)) != 0,] 
    Error in (function (classes, fdef, mtable)  :
      unable to find an inherited method for function 'exprs' for signature '"CellDataSet"'

Would it be possible to use `monocle3` with `cicero`?
Best,
Sameet

**Comment by hpliner** [comment]
@sameet @jeremycfd 
I have modified Cicero to be compatible with monocle3 on a separate branch, however the new documentation is not yet complete. You can install this branch using :
`devtools::install_github('cole-trapnell-lab/cicero-release', ref="monocle3)`

but it will be another week likely before the website is updated to reflect the changes

**Comment by sameet** [comment]
@hpliner 
Thank you.  I see your changes.  I have started following the website.md vignette with my data.  I will let know how it goes.

**Comment by hpliner** [comment]
Thanks for you patience, Cicero now has updated web documentation and a few bug fixes on the monocle3 branch. It should be good to go for interoperability with Monocle 3!
