### ISSUE TITLE
Link to a page is broken.

### ISSUE THREAD

**Issue by sameet** [cole-trapnell-lab/cicero-release#31]
https://cole-trapnell-lab.github.io/monocle3/docs/#analyzing-branches-in-single-cell-trajectories link is broken.

**Comment by hpliner** [comment]
Where is it linked?

**Comment by sameet** [comment]
It gives a 404 error.

**Comment by hpliner** [comment]
Right, but where did you find the link? On the website?

**Comment by sameet** [comment]
Its at the bottom of the page.

**Comment by sameet** [comment]
I also realized that it is not just that link that is not working, bottom 4 links are not working.  Only the top links are working.

**Comment by hpliner** [comment]
I think this was referring to the vignette, which is updated. Reopen if not fixed
