### ISSUE TITLE
Is there "data(gene_annotation_sample)" file for hg38 in cicero in step of Constructing cis-regulatory networks? Thank you so much.

### ISSUE THREAD

**Issue by MQMQ2018** [cole-trapnell-lab/cicero-release#33]
Dear Drs. Hannah Pliner and Cole Trapnell,

Is there "data(gene_annotation_sample)" file for hg38 in cicero in step of Constructing cis-regulatory networks? Thank you so much.

Best,
Qi

**Comment by hpliner** [comment]
Excellent timing, I was just adding instructions for making your own in our new FAQ section on the website! See here: https://cole-trapnell-lab.github.io/cicero-release/docs_m3/#frequently-asked-questions

**Comment by MQMQ2018** [comment]
Thank you, Hpliner for your quickly response, I will check it tomorrow. 
Have a nice weekend!

Best,
Qi
