### ISSUE TITLE
About CellDataSet and cell_data_set

### ISSUE THREAD

**Issue by dhoneyi** [cole-trapnell-lab/cicero-release#38]
I use cicero to analyse my scATAC data from 10X, when I create the cds object use the code "input_cds <-  suppressWarnings(new_cell_data_set(indata,
                                                 cell_metadata = cellinfo,
                                                 gene_metadata = peakinfo))", the output is "Large cell_data_set", not "Large CellDataSet".But the input of make_cicero_cds should be "Large CellDataSet".So how can I solve this problem?The error shows :"Error: is(object = cds, class2 = "CellDataSet") is not TRUE"

**Comment by hpliner** [comment]
You need to make sure that you are using monocle and cicero main branch OR monocle3 and cicero monocle3 branch.  Mixing them is not compatible. Take a look at the two different pages here: https://cole-trapnell-lab.github.io/cicero-release/docs/ and here: https://cole-trapnell-lab.github.io/cicero-release/docs_m3/ to see the different installation instructions.
