### ISSUE TITLE
estimateDispersion Issue

### ISSUE THREAD

**Issue by zillerm** [cole-trapnell-lab/cicero-release#41]
Dear Cicero Team,

when running aggregate_by_cell_bin on an scATAC dataset, I am receiving the following error:
 binned_input_lin <-aggregate_by_cell_bin(input_cds, "combinedId")
|======================================================|100% ~0 s remaining     Error in parametricDispersionFit(disp_table, verbose) : 
  Parametric dispersion fit failed. Try a local fit and/or a pooled estimation. (See '?estimateDispersions'

and these warnings:
Warning messages:
1: In log(ifelse(y == 0, 1, y/mu)) : NaNs produced
2: step size truncated due to divergence

I ran cicero on this dataset before but with a different cell clustering and filtering and it worked fine. 

It looks like the fit is consistently failing but I don't understand why. There are no empty samples/cells or peaks that are not present in at least of the clusters.
I would appreciate any suggestions.

Thanks a lot,
Michael

**Comment by hpliner** [comment]
This usually occurs when there are peaks that only have accessibility in very few bins. Can you try filtering the very lowly accessible peaks and see if that solves the problem? 

Alternatively, in monocle3 we no longer use dispersion estimates in the same way which would avoid the problem entirely. To use monocle3, you would install monocle3 according to instructions here: https://cole-trapnell-lab.github.io/monocle3/docs/installation/ and then install cicero for monocle3 using the instructions and documentation here: https://cole-trapnell-lab.github.io/cicero-release/docs_m3/#installing-cicero

**Comment by hpliner** [comment]
I'm going to close this issue due to lack of reply. Reply/reopen if this continues to be an issue.
