### ISSUE TITLE
Question for trajector analysis

### ISSUE THREAD

**Issue by crushseven-7** [cole-trapnell-lab/cicero-release#46]
Hi,
Thank you for your wonderful software. Currently I am working on scATAC-seq data trajectory analysis. After I prepared input_cds and run estimate_size_factors() function, I got this error:
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'counts' for signature '"CellDataSet"'
How shall I modify the input cds to avoid this error?

Thank you,
Best,
Yan

**Comment by hpliner** [comment]
Hi Yan,

This error occurs when you're mixing monocle and monocle3. You have to make sure you have either monocle3 and cicero for monocle3 (see [here](https://cole-trapnell-lab.github.io/cicero-release/docs_m3/#installing-cicero)) or monocle and cicero for monocle (see [here](https://cole-trapnell-lab.github.io/cicero-release/docs/#installing-cicero))

Hope this helps

**Comment by crushseven-7** [comment]
Thank you for your helpful info. Last time I install cicero in coda with command `conda install -c bioconda bioconductor-cicero` . In retrospect, this cicero is for monocle.
