### ISSUE TITLE
Question for aggregated cells

### ISSUE THREAD

**Issue by hejing3283** [cole-trapnell-lab/cicero-release#47]
Is there any way of keeping the original cell metadata and still link back the agg cells to the original single cells?

**Comment by hpliner** [comment]
What function are you asking about? aggregate_by_cell_bin ? If so, then this isn't currently implemented. Depending on how you'd like the aggregation to occur, this could be managed fairly straightforwardly with the [tidyverse](https://r4ds.had.co.nz/transform.html#grouped-summaries-with-summarise). If make_cicero_cds, then you can pass the column names of numeric metadata with the parameter `summary_stats` and the mean will be added to the new colData table.

**Comment by hpliner** [comment]
Closing, reopen if this is still an issue
