### ISSUE TITLE
Could not find function "newCellDataSet"

### ISSUE THREAD

**Issue by cartal** [cole-trapnell-lab/cicero-release#48]
I have installed `cicero` as described [here](https://cole-trapnell-lab.github.io/cicero-release/docs_m3/). But when I run it, I get the following error:

```
Error in newCellDataSet(indata, phenoData = pd, featureData = fd, expressionFamily = VGAM::binomialff(), : could not find function "newCellDataSet"
```

When I use another R environment and I install the old `monocle` it works until this step:

```
input_cds <- preprocessCDS(input_cds, norm_method = "none")
```
where it fails because the `preprocessCDS` doesn't exists, which is what happens when you have the old `cicero` instalation. 

Do you know how to solve this with the new `monocle3`-compatible `cicero`?

**Comment by hpliner** [comment]
Hello, if you're using the new monocle3-compatible version, then you/the code should not be running newCellDataSet. Can you post what step you're getting that error for, and your sessionInfo() ?

**Comment by hpliner** [comment]
Closing, reopen if this is still an issue
