### ISSUE TITLE
multi-sample

### ISSUE THREAD

**Issue by TheSallyGardens** [cole-trapnell-lab/cicero-release#51]
Hi!
Good tool!
How does cicero handle multi-sample data?
How to eliminate batch effect?

**Comment by hpliner** [comment]
Hi, Please post questions to the [google group](https://groups.google.com/forum/#!forum/cicero-users) in future and only use github for bug reports.

Cicero does not have an explicit way to handle batch effects, however the dimensionality reduction coordinates used for aggregating cells in make_cicero_cds can come from a batch corrected analysis, like that you can do with Monocle3, [described here](https://cole-trapnell-lab.github.io/monocle3/docs/clustering/#batch-effects). Depending on the nature of your experiment, you can also run cicero separately on each sample.
