### ISSUE TITLE
cannot go through reduceDimension()

### ISSUE THREAD

**Issue by wangmhan** [cole-trapnell-lab/cicero-release#54]
I used cicero version 1.4.4 wrapped with monocle.
The analysis get stuck when run reduceDimension(), 
Error: vector memory exhausted (limit reached?).
This is on my laptop, I also tried on server, while get killed.

Do you have any solutions for that?

I tried to switch to the new version wrapped with monocle3 as well, but cannot get it installed.

**Comment by hpliner** [comment]
I'm afraid you'll need to upgrade to monocle3 - monocle has certain data size limits (part of why monocle3 was written). What was your issue with installation? And have you posted the installation issue to the monocle3 github?

**Comment by wangmhan** [comment]
Thanks for the reply. No, I tried to install cicero monocle3 version in
both server and on my own Mac system all failed.
As cicero monocle version worked, I have the expectation to go through this
version if could add some cutoff before run reduce dimension step?

The error I met for monocle3:
On server:
devtools::install_github("cole-trapnell-lab/cicero-release", ref =
"monocle3")
ERROR: dependency ‘monocle3’ is not available for package ‘cicero’
* removing
‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/cicero’
Error: Failed to install 'cicero' from GitHub:
  (converted from warning) installation of package
‘/var/folders/wk/lz78d33s61v7sd01z6495q340000gp/T//RtmpnX8dli/file148a4dddcd57/cicero_1.3.4.8.tar.gz’
had non-zero exit status


devtools::install_github('cole-trapnell-lab/monocle3')
take quite some time after check step, always get stuck during the
installation
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘sf’

install.packages("sf")
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘rgdal’

On Mac laptop:
just get stuck somewhere after the checking step.

**Comment by hpliner** [comment]
https://cole-trapnell-lab.github.io/monocle3/docs/installation/#troubleshooting There is some information on installing 'sf' at this link, hopefully that gets you past the errors

**Comment by hpliner** [comment]
Marking this as a monocle3 error - if you're still having trouble with an install, please open an issue there!
