### ISSUE TITLE
run Cicero on whole data or subsets?

### ISSUE THREAD

**Issue by Brawni** [cole-trapnell-lab/cicero-release#55]
Hello!

Thanks for this great package! I have a dataset including of a cluster of cancer cells and several othesr of normal cells within the same sample. I'm trying to understand if it's better to run Cicero on the whole cells or subset first for cancer and normal cells and then run Cicero on each subset. More generally, if I have an heterogeneous group of cells in a UMAP space, should I run Cicero on subsets of these to avoid smaller clusters signal to be lost? And what is the lower limit of number of cell on which Cicero can reliably calculate correlations? 

Thanks for your support and hope this makes sense!

**Comment by hpliner** [comment]
It's going to depend a bit on what you're looking for and how different the two cells are. If you're just looking for an overall map of co-accessibility and the cell types aren't that different, then you can run Cicero on the two together. If the cell types are quite different, or you're interested in potential changes in co-accessibility, then you'll want to run them separately. 

As far as lower limits, the lowest number I've personally worked with is a few hundred, but I suspect this will depend significantly on both the variation in the dataset, and the depth/sparsity of the methods.

In future, please post questions to the google group here: https://groups.google.com/forum/#!forum/cicero-users and leave Issues for bug reports - makes it easier to future users to find answers!

**Comment by Brawni** [comment]
Hi Hannah, thanks a lot for your answer and sorry if I didn't post it in the right section!
