### ISSUE TITLE
make_cicero_cds reports input object class error

### ISSUE THREAD

**Issue by MagpiePKU** [cole-trapnell-lab/cicero-release#57]
Hi,

I ran into a strange error like : 
> cicero_cds <- make_cicero_cds(cds = input_cds, reduced_coordinates = umap_coords,k = 50,summary_stats = 'num_genes_expressed',size_factor_normalize = F)
Error: is(object = cds, class2 = "CellDataSet") is not TRUE

the input object is like: (created by monocle3)
> class(input_cds)
[1] "cell_data_set"
attr(,"package")
[1] "monocle3"

I wonder whether this is due to an issue of change version of monocle? 

Thanks,
Yi

PS sessionInfo is: 

![image](https://user-images.githubusercontent.com/7695551/84149446-12c47200-aa93-11ea-986a-3e35667d79f1.png)

**Comment by hpliner** [comment]
Hello,

In order to use cicero with monocle3, you have to install the 'cicero for monocle3' version. You'll find instructions on that here: https://cole-trapnell-lab.github.io/cicero-release/docs_m3/#installing-cicero

Reopen if that doesn't solve your issue!
