### ISSUE TITLE
# cell ordering can be done interactively by leaving out "root_cells"

### ISSUE THREAD

**Issue by sylestiel** [cole-trapnell-lab/cicero-release#60]
input_cds <- order_cells(input_cds, 
                         root_cells = "GAGATTCCAGTTGAATCACTCCATCGAGATAGAGGC")

What does this sequence equate to?

Thanks!

**Comment by hpliner** [comment]
Hello, that line refers to the name of a cell (i.e. column name of the expression matrix that refers to that cell). In the example data, the cells were named based on a barcode sequence. For more info on order_cells, see the monocle3 docs [here](https://cole-trapnell-lab.github.io/monocle3/docs/trajectories/#order-cells)!
