### ISSUE TITLE
A question about generate_ccans() results

### ISSUE THREAD

**Issue by chent5** [cole-trapnell-lab/cicero-release#61]
Thanks a lot for developing this package.

I checked the pairwise co-accessibility of a CCAN detected by generate_ccans() function. I found that there are also some negative values of co-accessibility. Here are my code:
<img width="403" alt="image" src="https://user-images.githubusercontent.com/40006284/88616170-6f8ae480-d061-11ea-9ebc-942675c14612.png">

I am a little confused... CCANs are clusters of sites that tend to be co-accessible. How to explain these negative values for the peaks in the same CCAN? Or is there anything wrong with my code or my understanding?

Thanks so much for your help in advance!

**Comment by hpliner** [comment]
Hello,
CCANs are clusters of coaccessible sites as determined by finding modules within a graph where edges have positive coaccessibility. This doesn't exclude the possibility that there are pairs of sites within that module that have negative coaccessibility values. In the above code you are sorting by coaccessibility, I suspect there are many more positively coaccessible pairs further down the list!
