### ISSUE TITLE
Error message when running generate_ccans()

### ISSUE THREAD

**Issue by chent5** [cole-trapnell-lab/cicero-release#62]
Thanks a lot for developing this package.

After I computed coaccessibility cluster by cluster using run_cicero() and got the conns object. I got an error message when running generate_ccans() as below:
"Error in make_ccan_graph(connections_df, coaccess_cutoff = coaccess_cutoff) : 
  No connections for graph"

The above error message only occurred in some of the clusters, not all of them. I am confused about what cause this error? Could you help to solve this problem? Thank you so much!

**Comment by hpliner** [comment]
Answered in the user group here: https://groups.google.com/g/cicero-users/c/rE73PyjHTEc
