### ISSUE TITLE
Multiple peak tracks

### ISSUE THREAD

**Issue by johannesnicolaus** [cole-trapnell-lab/cicero-release#65]
Hi, I realized that when plotting peak connections `plot_connections`, I get multiple peak tracks depending on the size of the output device. When the output device size is large, there is only one peak track, but the text is barely visible, and when I make it smaller, multiple track appears (which seems to be subsets of the original track. Also, in your advanced visualization section of the Cicero manual page, there are also some plots with multiple tracks of peaks. Is there any reason that this might have happened?

This might also be related to another issue I find where I tried to use `return_as_list()`  and `plotTracks()`, the peaks would just stack on top of each other, just like the issue I mentioned above, but I get not only 2 or 3 tracks, but as many tracks as there are peaks.

**Comment by hpliner** [comment]
Hello, This is a function of Gviz, which is the track plotting package that underpins plot_connections. When there isn't enough horizontal space to plot the peaks without them overlapping, then it automatically staggers them in multiple rows. With a wide enough device, they should all end up in one row. As for the return_as_list issue, I'm not sure what might be causing this. Can you post the code you're using to generate it?

**Comment by johannesnicolaus** [comment]
Hi, thanks for the response. I'm also not sure what was causing that, I managed to fix that for now (I think changing the device was what did the trick.
