### ISSUE TITLE
Error message when running aggregate_by_cell_bin()

### ISSUE THREAD

**Issue by chent5** [cole-trapnell-lab/cicero-release#66]
I am using Cicero/Monocle3 tutorial by this link https://cole-trapnell-lab.github.io/cicero-release/docs_m3/#single-cell-accessibility-trajectories. I have generate a cell_data_set object named "input_cds_lin" and have successfully computed peudotime. But when I tried to run aggregate_by_cell_bin(), I got an error message saying "Error: is(object = cds, class2 = "CellDataSet") is not TRUE".

Please see my code below
![image](https://user-images.githubusercontent.com/40006284/91643308-f08e2080-e9ff-11ea-8917-4e95bf988bd2.png)

Could you help to solve this problem? Thank you so much!

**Comment by hpliner** [comment]
That message is caused by mixing monocle2 and cicero for monocle3 or vis versa. Can you please post your sessionInfo()?

**Comment by chent5** [comment]
I restart R and ran the code again. There is no error any more... Probably, I loaded too many packages yesterday. Thanks a lot for your help.
