### ISSUE TITLE
data("mouse.mm9.genome")

### ISSUE THREAD

**Issue by elachtarajax** [cole-trapnell-lab/cicero-release#67]
Is the mouse genome only available with Monocle 3? It does not appear to be an exported object from the regular Cicero package (under the data folder).

**Comment by hpliner** [comment]
I don't believe it's available in either of the versions. We include the human as a reference only. You can build your own following the instructions here: https://cole-trapnell-lab.github.io/cicero-release/docs_m3/#frequently-asked-questions

**Comment by elachtara** [comment]
Hi- Thank you for the response, I will use the human for now. Do the human annotations from your pseudo-bulk apply to bulk ATAC as well?
