### ISSUE TITLE
Transfering mapping info from one object to another

### ISSUE THREAD

**Issue by aleksandrPi** [cole-trapnell-lab/cicero-release#69]
Hi monocle/cicero team,

I have a question about both version 2 and 3 of your lovely monocle. I am using cicero to create a developmental trajectory from atac-seq data. This works fine, but I want to next create monocle CDS objects containing either TSS activity or chromVAR motif enrichment with my own normalizations, and subsequently I want to transfer the mapping and graph info from the initial atac-seq peaks CDS object to those two, so that I can visualize the dynamics of TSS activity or motif enrichemnt on the same graph. 
N.B. I tried to just steal the following metadata from the initial object, but I am not 100% sure if its the best way to do it. What do you think?
new_cds@reducedDimS                 <-  original_cds@reducedDimS    
new_cds@cellPairwiseDistances   <-  original_cds@cellPairwiseDistances  
new_cds@reducedDimA                <-  original_cds@reducedDimA 
new_cds@minSpanningTree          <-  original_cds@minSpanningTree 
new_cds@dim_reduce_type          <-  original_cds@dim_reduce_type        

Thank you!

**Comment by hpliner** [comment]
Hi, what happens when you attempt to run it/continue your analysis? Off the top of my head I think that might work - I believe you're replacing everything necessary, but depending on which downstream steps you are hoping to use, they may or may not work.

**Comment by aleksandrPi** [comment]
It seems to work well, only thing that is not getting transferred is the branch-points from the old trajectory, I could not find where they are contained...

**Comment by hpliner** [comment]
The branch points are stored in cds@auxOrderingData, might try transferring that as well

**Comment by hpliner** [comment]
Going to close, let me know if you have further issues
