### ISSUE TITLE
Error with creating cicero CDS

### ISSUE THREAD

**Issue by eliduong** [cole-trapnell-lab/cicero-release#7]
Hi!  I'm getting this error with make_cicero_CDS function.

cicero_cds <- make_cicero_cds(input_cds, reduced_coordinates = umap.emb, k = 50)
Error in parametricDispersionFit(disp_table, verbose) :
 Parametric dispersion fit failed. Try a local fit and/or a pooled estimation. (See ‘?estimateDispersions’)

My input_cds has about 8k cells and 100k peaks.  These are the overlap QC metrics.
Maximum shared cells bin-bin: 44
Mean shared cells bin-bin: 0.322901408806195
Median shared cells bin-bin: 0

Thanks!

**Comment by hpliner** [comment]
Hi, this is an issue with the BiocGenerics “estimateDispersions” call internal to make_cicero_cds. I’ve seen this before when there are cells with zero or very few reads. Have you tried removing low read cells and trying again?

**Comment by eliduong** [comment]
I've selected for cells with more than 2k reads and an average of 10k reads for group.  Would you recommend increasing the lower threshold?

**Comment by hpliner** [comment]
Hmm, I'd expect that to be high enough, but maybe try a very high threshold just to see if we're on the right track? The other place I've seen this is if there are a set of cells that are major outliers with respect either to read depth or overall expression. Is this possible in your dataset?

**Comment by eliduong** [comment]
There are min and/or max thresholds set for both already. Trying a higher parameter for # cells per peak and then, I will also try setting the reads per cell higher as well. Taking a bit to run so will get back to you.

**Comment by hpliner** [comment]
Great, let me know how it goes. BTW, a recently merged pull request should speed things up for you, I recommend updating

**Comment by eliduong** [comment]
Oh nice!  Thanks for the tip.

**Comment by eliduong** [comment]
Ended up with the same error after increasing # cells per peak and reads per cell.  I also tried with the updated cicero. Any other thoughts?

**Comment by hpliner** [comment]
Hmm, sorry the suggestions didn't work. One last try: are there any nans or NAs in your dataset?

**Comment by hpliner** [comment]
I just pushed a new version with no estimateDispersions call. That call isn't needed for typical cicero downstream functions

**Comment by eliduong** [comment]
We were able to get make_cicero_cds to work by decreasing k to 25 over the weekend.  I will try it with no estimateDispersions if we run into any issues.  Thanks Hannah!
