### ISSUE TITLE
quick ATAC-seq question

### ISSUE THREAD

**Issue by widsquid** [cole-trapnell-lab/cicero-release#71]
Hello and thank you for the great tools,

I am attempting to run through the cicero differential accessibility pipeline and seem to be ending up with nothing (or less than 5) DA peaks after the subset for pseudotime_terms step. Any thoughts on why that might be occurring? my length(binned_input_lin) is 171221 and length(fit_coefs$p_value) is 2982 so it seems to be related to the q_value filter. I noticed binomial expression_family is recommended for ATAC and so was wondering why that is not in the vignette rather it uses the default. In any case I see why as when I attempted it instead the status of every peak was FAIL. The data comes from a rather large aggregated 10x output however please let me know if there is anything in particular I can show that would give any clues. Thanks so much.
W

**Comment by hpliner** [comment]
Hello, The reason that the expression family is not binomial is that the differential expression is run on an aggregated dataset which should move into the normal approximation. As to why your data is not giving any DA peaks, it is hard to say without more information. Do you have a well fit pseudotime curve? Are the data very homogenous? Perhaps I could help with further information.

**Comment by hpliner** [comment]
I'm going to close, reopen if you have further questions

**Comment by widsquid** [comment]
Sorry for the delay, thanks so much for your reply, suggestions and invitation to reopen at a later time.
W

On Mar 25, 2021, at 12:27 PM, Hannah A Pliner ***@***.***> wrote:

﻿

I'm going to close, reopen if you have further questions
