### ISSUE TITLE
plot_connects() font unreadable

### ISSUE THREAD

**Issue by wfma** [cole-trapnell-lab/cicero-release#74]
Hi! 

I am loving cicero, the plot_connections() functions however is giving me graphs with fonts too small to read:

```
plot_connections(conns, "chr3", 138318140, 138.85977 ,
                 gene_model = gene_anno, 
                 coaccess_cutoff = 0, 
                 connection_width = 3, 
                 peak_color = "skyblue3",
                 connection_color = "chocolate",
                 connection_color_legend = TRUE,
                 alpha_by_coaccess = FALSE,
                 connection_ymax = NULL,
                 collapseTranscripts = "longest" ) 
```

![image](https://user-images.githubusercontent.com/23326773/110395681-8f917600-803c-11eb-8925-7b550172de80.png)

What is the best way to increase this font size?

Thanks,
Wei

**Comment by hpliner** [comment]
Hi Wei,

So unfortunately most of the text sizes are based on the size of the device, so if you plot to a smaller device, then the fonts will be proportionally bigger (i.e. use png() with 2 x 3 inches). The other option is to customize everything with https://cole-trapnell-lab.github.io/cicero-release/docs_m3/#advanced-visualizaton. The Gviz user guide has tons of options to choose from.

**Comment by hpliner** [comment]
Going to go ahead and close, reopen if there are further issues
