### ISSUE TITLE
How to extract dimension data after clustering in monocle3

### ISSUE THREAD

**Issue by yanhaidong1** [cole-trapnell-lab/cicero-release#75]
Hi,

I just updated the cicero from monocle2 to monocle3 and found there are some functions lost. 
eg. I want to extract dimension using cds@reducedDimA or cds@reducedDimS but these two are disappeared. Where do I find the dimension data after doing the 'reduce_dimension' and 'cluster_cells'? I will to replace them by my own clustering dimension. 

Best wishes,
Haidong

**Comment by hpliner** [comment]
Hello, with the new cds functions, you can get the dimension reduction coordinates using "reducedDims(cds)"

**Comment by yanhaidong1** [comment]
Got it. Thanks a lot!
