### ISSUE TITLE
Correlation between gene expression and cicero activity

### ISSUE THREAD

**Issue by AnjaliC4** [cole-trapnell-lab/cicero-release#79]
Hi, thank you for this awesome tool!
I noticed that correlations between promoter activity (snATAC) and gene expression (snRNA) for the same subject and cell-type is much higher (R=0.5) than that between cicero gene activity and gene expression (R=0.18).  I wonder if non-specific enhancer accessibility is adding to some noise. Perhaps that I am comparing cicero normalized gene activity to snRNA gene expression (created with Seurat) are on different scales - not sure. What are your thoughts on this?

**Comment by hpliner** [comment]
Hi, sorry for the delay. I'm not sure what might be causing this, could be non-specific enhancer as suggested. One thing to do is to plot the two metrics against each other and see where the lack of correlation is coming from, i.e. is it that there are a lot of zeros in expression and not in activity, lots of very low values, etc. I wouldn't expect the different scales to impact the correlation much, but you could try a rank-based metric (e.g. Spearman) to be sure.
