### ISSUE TITLE
Filtering genomic_coords in estimate_distance_parameters() ?

### ISSUE THREAD

**Issue by hypercompetent** [cole-trapnell-lab/cicero-release#8]
It looks like estimate_distance_parameters() will run generate_windows() on all of the chromosomes provided in genomic_coords, even if there aren't any reads in the cds for those chromosomes.

In some cases, I think this can cause a lot of iterations to find no values in the win_range, resulting in no distance parameter estimate because length(distance_parameters) < sample_num at the end of the iterations.

Would it make sense to add a filtering step before generate_windows() to keep only the chromosomes with any reads in the cds, or should users filter genomic_coords before run_cicero()?

I ran into this by trying to run cicero on separate chromosomes in parallel, and got a lot of failed distance parameter estimates because most of the windows were on different chromosomes. Maybe this is an edge case, or doesn't match how you expect the functions to be used, in which case you could skip this suggestion :)

Thanks!
-Lucas

**Comment by hpliner** [comment]
Hi Lucas,

Thanks for the suggestion. I didn't anticipate this use case, so yes, it could be useful - I'll try to include it in the next update. In the meantime, filtering using genomic_coords should have the same effect, like you noted!

Hannah

**Comment by hpliner** [comment]
I think I'm going to leave this to be done by filtering in genomic_coords for the moment. If you think this is still an important feature, reopen! Thanks for the suggestion!
