### ISSUE TITLE
[Cicero in GM12878/K562 cell lines data ]

### ISSUE THREAD

**Issue by dhoneyi** [cole-trapnell-lab/cicero-release#81]
I would use Cicero to calculate co-accessibility score in GM12878 scATAC-seq dataset. Since the GM12878 is cell line data, I wonder why can I used Cicero on cell line dataset. For example, I have a GM12878 data containing ~20,000 cells and ~240,000 peaks. Or can you share me the co-accessibility scores information in your Pliner et al., 2018, Molecular Cell 71, 858–871. Thanks!

**Comment by hpliner** [comment]
Hi, you can use Cicero on cell line data in the same way you would with any other data. See the instructions here: https://cole-trapnell-lab.github.io/cicero-release/docs_m3/

The scores from GM from the original paper are available as a gzipped csv here: https://drive.google.com/file/d/14Mfs6vlKX8tQGRnEpl_xPpPHo33nIgAB/view?usp=sharing
