### ISSUE TITLE
interpretation of generate_ccans output

### ISSUE THREAD

**Issue by pengxin2019** [cole-trapnell-lab/cicero-release#82]
Hi cicero developers,
I am cicero user Penny and have a question in terms of the `generate_ccans` output. I am posting my question rather than issue here since I could not find discussion session in your Github account.

Here is the `conns` generated by running `run_cicero`:
```
# > head(conns)
# Peak1             Peak2 coaccess
# 1 1-10000487-10000841 1-9756605-9757134        0
# 2 1-10000487-10000841 1-9761378-9762238        0
# 3 1-10000487-10000841 1-9765446-9766266        0
# 4 1-10000487-10000841 1-9767710-9768302        0
# 5 1-10000487-10000841 1-9770505-9770826        0
# 6 1-10000487-10000841 1-9784557-9785255        0
 > dim(conns)
# [1] 556348      3
```

Here is the ccans object generated by running `ccans <- generate_ccans(conns)`
```
# > head(ccans)
# Peak CCAN
# 1-100018539-100019553 1-100018539-100019553    1
# 1-100058819-100059526 1-100058819-100059526    1
# 1-100077390-100078099 1-100077390-100078099    1
# 1-100088559-100089520 1-100088559-100089520    1
# 1-100092950-100093504 1-100092950-100093504    1
# 1-100107061-100109125 1-100107061-100109125    1

# > tail(ccans)
# Peak CCAN
# 1-9952587-9953591 1-9952587-9953591    3
# 1-9977908-9978682 1-9977908-9978682    4
# 1-9982936-9983670 1-9982936-9983670    4
# 1-9986231-9988884 1-9986231-9988884    4
# 1-9991751-9994508 1-9991751-9994508    3
# 1-9996577-9997469 1-9996577-9997469    4

```
Can you tell me what is the meaning of the `CCAN` column?  For example, for the rows with value 1 in CCAN column, does it mean all these rows belong to the same CCAN? In other words, are all these rows/regions  in the same colored box in  figure below?

![image](https://user-images.githubusercontent.com/54915282/149218806-6749e7b1-98ac-453d-b60d-4b900a3df764.png)

Thanks
Best
Penny

**Comment by hpliner** [comment]
Hi Penny,

Sorry for the delay. Yes, the CCAN column tells you which CCAN each row belongs to, so all of the rows with CCAN of 1 belong to CCAN 1, etc.

In future, questions can be posted here: https://groups.google.com/g/cicero-users

Hope this helps
