### ISSUE TITLE
 reduceDimension:Error in if (any(i < 0L)) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by yuxuanChen777** [cole-trapnell-lab/cicero-release#83]
```
input_cds <- make_atac_cds(A, binarize = TRUE)

data("human.hg19.genome")
set.seed(2017)
input_cds <- detectGenes(input_cds)
input_cds <- estimateSizeFactors(input_cds)
save(input_cds,file = 'input_cds.RData')
input_cds <- reduceDimension(input_cds,num_dim=50, max_components = 2,reduction_method = 'tSNE', norm_method = "none")
```
![image](https://user-images.githubusercontent.com/86239688/176456471-45d2f6c4-e1b8-4c50-a135-b157e91d3d51.png)

When I run this code, I met this error. I don't know why this error happened, please help me.Thank you

**Comment by hpliner** [comment]
Hello, this looks like an issue with monocle. When you run the example code with the example data starting here: https://cole-trapnell-lab.github.io/cicero-release/docs/#loading-data-from-a-simple-sparse-matrix-format are you able to get passed the error?

**Comment by yuxuanChen777** [comment]
I think the reason for the error is  the number of samples(70000) in my dataset is large

**Comment by hpliner** [comment]
Closing, reopen if this remains an issue
