### ISSUE TITLE
no transcrition structures in plot_connection

### ISSUE THREAD

**Issue by ccshao** [cole-trapnell-lab/cicero-release#85]
Thanks for the nice package. 
When using mm10 gtf, the transctiption structures are not shown. Genes are shown as a continuous blocks.

Here is code getting the mm10 annotations
```
temp <- tempfile()
download.file("ftp://ftp.ensembl.org/pub/release-102/gtf/mus_musculus/Mus_musculus.GRCm38.102.gtf.gz", temp)
gene_anno <- rtracklayer::readGFF(temp)
unlink(temp)

gene_anno$chromosome <- paste0("chr", gene_anno$seqid)
gene_anno$gene       <- gene_anno$gene_id
gene_anno$transcript <- gene_anno$transcript_id
gene_anno$symbol     <- gene_anno$gene_name
saveRDS(gene_anno, "mm10_gtf.rds")
```

And plotting
```
plot_connections(conns, "chr4", 104355245, 104436442,
                 gene_model          = gene_anno,
                 coaccess_cutoff     = .25,
                 connection_width    = .5,
                 collapseTranscripts = "longest")
```

In the  output, genes are shown as blocks.

![Screenshot_2022-10-05_11-00-32](https://user-images.githubusercontent.com/4980631/194025787-e4ef8d6d-f27c-4b73-8abb-6411c82dbb53.png)

**Comment by hpliner** [comment]
Hello, sorry for the delay. It looks like the reference you downloaded includes full gene and transcript entries which would override the exon annotations. If you filter by type to only include exons that should solve the issue. If not, reopen!
