### ISSUE TITLE
run_cicero error

### ISSUE THREAD

**Issue by tkisss** [cole-trapnell-lab/cicero-release#86]
Hi,  thanks for this nice package!

There is an error when I run **run_cicero** function.

`data("human.hg19.genome")`
`sample_genome <- subset(human.hg19.genome, V1 == "chr2")`
`sample_genome$V2[1] <- 10000000`
`conns <- run_cicero(cicero_cds, sample_genome, sample_num = 2)`

> Warning message in estimate_distance_parameter(cicero_cds, genomic_coords = sample_genome):
"Could not calculate sample_num distance_parameters (0 were calculated) - see documentation details"
Error in estimate_distance_parameter(cicero_cds, genomic_coords = sample_genome): No distance_parameters calculated
Traceback:
> 1. estimate_distance_parameter(cicero_cds, genomic_coords = sample_genome)
> 2. stop("No distance_parameters calculated")

Any idea for solving this problem?

Thanks!

**Comment by hpliner** [comment]
Hello, are you running this on your own data or on the example data? For your own data, you should remove the sample_genome lines and set the sample_num parameter to something much larger (default is 100). These lines were included only so the example would run quickly.

**Comment by tkisss** [comment]
Hi, I run the _run_cicero_ on my own data. Following your suggestion, I tried removing the sample_genome lines and resetting the sample_num parameter to 100, but the same error persists.

But fortunately I found the problem, _new_cell_data_set_ receives dense format data, not sparse format data! After converting the input data from sparse to dense. It worked!

Many thanks!

**Comment by tkisss** [comment]
Hi,

Fortunately, I found the problem! 

Cicero requires peak names in the form chrx_start_end, whereas the peak names in my data are in the form chr:start-end. After I converted the form of the peak names, it worked!

Many thanks!
