### ISSUE TITLE
length of Dimnames[[1]] (115668) is not equal to Dim[1] (147955)

### ISSUE THREAD

**Issue by midichlorianrich** [cole-trapnell-lab/cicero-release#87]
Hi,
I am tryin to make the CDS object.

# Read in matrix data using the Matrix package
indata <- Matrix::readMM(paste0(data_folder, "/matrix.mtx")) 
# Binarize the matrix
indata@x[indata@x > 0] <- 1

# Format cell info
cellinfo <- read.table(paste0(data_folder, "/barcodes.tsv"))
row.names(cellinfo) <- cellinfo$V1
names(cellinfo) <- "cells"

# Format peak info
peakinfo <- read.table(paste0(data_folder, "/peaks.bed"))
names(peakinfo) <- c("chr", "bp1", "bp2")
peakinfo$site_name <- paste(peakinfo$chr, peakinfo$bp1, peakinfo$bp2, sep="_")
row.names(peakinfo) <- peakinfo$site_name

row.names(indata) <- row.names(peakinfo)
colnames(indata) <- row.names(cellinfo)

# Make CDS
input_cds <-  suppressWarnings(new_cell_data_set(indata,
cell_metadata = cellinfo,
gene_metadata = peakinfo))

input_cds <- monocle3::detect_genes(input_cds)

#Ensure there are no peaks included with zero reads
input_cds <- input_cds[Matrix::rowSums(exprs(input_cds)) != 0,] 

But I keep getting this error

**row.names(indata) <- row.names(peakinfo)
Error in dimnamesGets(x, value) : 
  length of Dimnames[[1]] (115668) is not equal to Dim[1] (147955)**

My data comes from 10x Chromium Single Cell Multiome ATAC + Gene Expression

**Comment by hpliner** [comment]
Hi, These steps are for the import of a sparse matrix. It looks like the error is that the length of the peak info does not equal the number of rows in your sparse matrix. I would recommend loading your matrix in however best fits your data format and then you can skip to making the cds object with new_cell_data_set. See here on the monocle3 website for more information on building a cds object (https://cole-trapnell-lab.github.io/monocle3/docs/getting_started/#cell_data_set)

**Comment by hpliner** [comment]
Closing, reopen if this continues to be an issue
