### ISSUE TITLE
Hi, question about start using cicero

### ISSUE THREAD

**Issue by TauHHCC** [cole-trapnell-lab/cicero-release#88]
Hi, it is not an issue but about how can I start using cicero to analysis my scATAC data. 

My data is established by  plate based method, each cell has been labelled well. 
The data matrix I have now is the fragment file. I don't think it can be directly used to generate CDS in cicero since the fragment position is not peaks (actually I have tried, buy my R will die because the file is toooo big)?
If I would like to start from this fragment file, what should I do before loading them to cicero?

The fragment file can be accepted by ArchR. I was trying to extract the information from ArchR projects, but so far hasn't been succeed, and I don't know if I can. In ArchR, I couldn't find peak information before calling (I use MACS2), but after the calling, I can only find the information based on pseudo bulk data and grouped by every group, but I would like to have them in single cells to analysis in the cicero.

**Comment by hpliner** [comment]
Hello, apologies for the delay. You will definitely need the peak by cell matrix to run in cicero, but unfortunately I think you'll have to ask the maintainers of ArchR how to export that matrix. Alternatively, you could run MACS2 outside of ArchR and generate your matrix that way. Hope that helps

**Comment by hpliner** [comment]
Closing, reopen if you have additional issues
