### ISSUE TITLE
Questions about make_cicero_cds function

### ISSUE THREAD

**Issue by Abigail1l1l1l** [cole-trapnell-lab/cicero-release#89]
Dear author, 
    Thank you for developing such a useful tool. I have troubles when I want to check which cells are aggregated when I run the make_cicero_cds function. Could you please tell me If I can and how to get this information? Thanks a lot!

**Comment by hpliner** [comment]
Hello, If you run the function with the argument return_agg_info = TRUE, then the function will return a list with both the cds object and a data frame with this information. There are more details in the man pages about this function. Hope this helps
