### ISSUE TITLE
Question about differentialGeneTest

### ISSUE THREAD

**Issue by danielee0707** [cole-trapnell-lab/cicero-release#9]
I noticed that some of the examples in Cicero tutorial use num_genes_expressed in full model while others (also in Monocle tutorial) don't. What's the reason for that and when should we use it? Thanks!

**Comment by hpliner** [comment]
Adding the num_genes_expressed to the full model is a way of being extra conservative with ATAC data in making sure reads per cell/depth is accounted for. Strictly speaking it shouldn't generally be necessary since the calculation already takes Size_Factor into account. Hope this helps!
