### ISSUE TITLE
run_cicero Peak1 include NA

### ISSUE THREAD

**Issue by zhangqc723** [cole-trapnell-lab/cicero-release#92]
![image](https://github.com/cole-trapnell-lab/cicero-release/assets/86176443/12ca2c3b-17fa-4351-ac97-c83947a5473d)
When I check the result of **run_cicero**, I found the Peak1 or Peak2 include NA. Why? 
Tkans!

**Comment by zhangqc723** [comment]
Now, I met this error when I run this code _"ccans <- generate_ccans(conns)"_
Error in make_ccan_graph(connections_df, coaccess_cutoff = coaccess_cutoff) : 
  No connections for graph
But, this code _ccans <- generate_ccans(conns,coaccess_cutoff_override = 0.1)_ could be run enen if **coaccess_cutoff_override** was set 0.9.

**Comment by hpliner** [comment]
Hello, I'm going to need more info to look into this. Are any of your input peaks NA? Do they all follow the same chr-bp1-bp2 pattern?

**Comment by hpliner** [comment]
Closing from lack of activity. Please reopen if still an issue
