### ISSUE TITLE
Peak file for generating CDS

### ISSUE THREAD

**Issue by rb56** [cole-trapnell-lab/cicero-release#95]
Hello,

Im trying to run Cicero on scMultiome data (10x data) on 15 samples that have been integrated. I'm a little confused and unsure of the format of peaks file to make the Cell Data set object. In the tutorial (https://cole-trapnell-lab.github.io/cicero-release/docs_m3/) it mentions to use the matrix file however my dataset has aggregated data from 15 samples and Im not sure which input to use to generate the CDS.

Any help will be appreciated.

Thank you

**Comment by hpliner** [comment]
Hello, I'm not sure I have enough information to help, but I'd recommend taking a look at the monocle3 website for the various options for loading data here: https://cole-trapnell-lab.github.io/monocle3/docs/getting_started/#loading-data

However you end up with your cell data set object you should be able to continue with the cicero tutorial.
